### PR TITLE
Update sts support now that policy is ratified

### PR DESCRIPTION
**Pull request by lol768**
TODO: document changes made

### CODE REVIEW

**Comment by bendem** [comment]
Shouldn't both be supported for a while?

**Comment by mbax** [comment]
`STSHandlerTest` failed, @lol768  ;)

Also, were there any changes from draft to final that would mean just supporting both for now (`draft/sts` and `sts`) would be harmful?

**Comment by mbax** [comment]
@lol768 Can (/should) this be done soon? :)

**Comment by lol768** [comment]
It _should_ be done. Whether I'll be able to find the time to diff the specs and do it is another matter 😛

**Comment by kashike** [comment]
*pokes @lol768*

**Comment by mbax** [comment]
*pokes @lol768*

**Comment by lol768** [comment]
Is there a changelog that isn't just a `git diff`, somewhere..?

**Comment by Zarthus** [comment]
@lol768  https://kitteh.org/?

**Comment by lol768** [comment]
... for the spec

**Comment by mbax** [comment]
Thanks https://github.com/KittehOrg/KittehIRCClientLib/commit/c2b3c2881e3efa77020466fd97b3992333286db9

**Pull request closed without merging**
