### PR TITLE
Added: Channel#kick(User, String)

### PR DESCRIPTION
**Pull request by jkcclemens**
Ignore the branch name.

### CODE REVIEW

**Comment by jkcclemens** [comment]
Any fun feedback? Should the `@Nullable String reason` be a `@Nonnull Optional<String> reason`?

**Comment by kashike** [comment]
Assuming @mbax would like this PR to follow the rest of the codebase, there should be two methods: `void kick(@Nonnull User user)` and `void kick(@Nonnull User user, @Nonnull String reason)`.

**Comment by mbax** [comment]
As said on IRC, I don't feel this is any more beneficial than the existing `#newKickCommand()`

**Comment by jkcclemens** [comment]
```
[13:19:37]  <+jkcclemens>	so, Channel#kick
[13:19:54]  <+jkcclemens>	basically reduces the verbosity necessary to kick someone.
[13:20:15]  <+jkcclemens>	channel.newKickCommand().target(someDude).reason("Wow, you suck").execute() vs channel.kick(someDude, "Wow, you suck")
...
[13:21:15]  <+jkcclemens>	I also saw it here https://github.com/KittehOrg/KittehIRCClientLib/issues/33
...
[13:21:45]  <+jkcclemens>	just like Channel#op would be nice, rather than having to do a full-fledged mode command
[13:21:48]  <+jkcclemens>	convenience
```

**Comment by mbax** [comment]
Thanks! https://github.com/KittehOrg/KittehIRCClientLib/commit/a2438f3e7960f59acf83acc4c75aef2cbd89d354

**Comment by jkcclemens** [comment]
ayyy :3

**Pull request closed without merging**
