### PR TITLE
Add support for mbassador's new way of defining filters

### PR DESCRIPTION
**Pull request by kashike**
https://github.com/bennidi/mbassador/pull/150

### CODE REVIEW

**Comment by mbax** [comment]
This is non-breaking, right?

**Comment by kashike** [comment]
Correct.

**Comment by mbax** [comment]
Faaaabulous

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/0839ee427a73fc1e81b2d8f11288c68134cf6de1

Cherry-picked into 3.3.0! (Coming soon)

Thanks.

**Pull request closed without merging**
