### PR TITLE
Added: Simple .gitignore

### PR DESCRIPTION
**Pull request by jkcclemens**

### CODE REVIEW

**Comment by mbax** [comment]
Lacking justifiication. Forcing a .gitignore makes it frustrating for having your own custom one.

**Comment by jkcclemens** [comment]
How so? I have to add my own when I want to do work on the repo. If I add my own, I have to ignore it when committing. If one is included, it likely won't interfere, and if adjustments have to be made, they'll have to ignore the file when committing, just like if I had to add my own!

**Comment by mbax** [comment]
Bonus points for including .gitignore into it.

Also, you don't even have the target directory on this, which will immediately cause trouble for some folks.

**Comment by jkcclemens** [comment]
I would add `Goddammit mbaxter`, but I doubt you'd merge it.

**Comment by mbax** [comment]
Thanks!
https://github.com/KittehOrg/KittehIRCClientLib/commit/f47672ea07236522fd37f87e368ead14a7d59211

**Comment by jkcclemens** [comment]
ayyyyyyyyy :3

**Pull request closed without merging**
